# Generated by Django 3.1.4 on 2020-12-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('clothes', 'clothes'), ('shoes', 'shoes'), ('wathces', 'wathces'), ('laptops', 'laptops'), ('mobile phones', 'mobile phones'), ('headphones/headsets', 'headphones/headsets'), ('perfumes/deodrants', 'perfumes/deodrants'), ('accessories', 'accessories'), (' kid toys', ' kid toys'), ('HouseHold', 'HouseHold')], max_length=64, null=True),
        ),
    ]
