# Generated by Django 3.1.4 on 2020-12-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201215_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('clothes', 'clothes'), ('shoes', 'shoes'), ('watches', 'watches'), ('laptops', 'laptops'), ('mobile phones', 'mobile phones'), ('headphones/headsets', 'headphones/headsets'), ('perfumes/deodrants', 'perfumes/deodrants'), ('accessories', 'accessories'), ('kid toys', 'kid toys'), ('HouseHold', 'HouseHold')], max_length=64, null=True),
        ),
    ]
