# Generated by Django 3.1.4 on 2020-12-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.IntegerField(blank=True, max_length=11, null=True),
        ),
    ]
